### ISSUE TITLE
Could not find a part of the path "Content\Data\LeagueSandbox-Default\Items"

### ISSUE THREAD

**Issue by mrcyclo** [LeagueSandbox/GameServer#268] opened 2016-11-28 12:12 UTC
> (28/11/2016 7:07 PM) [EXCEPTION]: A first chance exception was thrown
(28/11/2016 7:07 PM) [EXCEPTION]: Could not find a part of the path 'E:\Games\InitWar\GameServer-master\GameServerApp\bin\Debug\Content\Data\LeagueSandbox-Default\Items'.
(28/11/2016 7:07 PM) [EXCEPTION]: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
(28/11/2016 7:07 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(28/11/2016 7:07 PM) [UNHANDLEDEXCEPTION]: Could not find a part of the path 'E:\Games\InitWar\GameServer-master\GameServerApp\bin\Debug\Content\Data\LeagueSandbox-Default\Items'.
(28/11/2016 7:07 PM) [UNHANDLEDEXCEPTION]: System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Games\InitWar\GameServer-master\GameServerApp\bin\Debug\Content\Data\LeagueSandbox-Default\Items'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at LeagueSandbox.GameServer.Logic.Content.ItemContentCollection.LoadItemsFrom(String directoryPath) in E:\Games\InitWar\GameServer-master\GameServerLib\Logic\Content\ItemCollection.cs:line 91
   at LeagueSandbox.GameServer.Logic.Content.ItemManager.LoadItems() in E:\Games\InitWar\GameServer-master\GameServerLib\Logic\Content\ItemManager.cs:line 40
   at LeagueSandbox.GameServer.Program.Run(String configPath, UInt16 serverPort) in E:\Games\InitWar\GameServer-master\GameServerLib\Program.cs:line 41
   at LeagueSandbox.GameServer.GameServerLauncher.LaunchServer(String configPath, UInt16 serverPort) in E:\Games\InitWar\GameServer-master\GameServerLib\Program.cs:line 15
   at LeagueSandbox.GameServerApp.Program.Main(String[] args) in E:\Games\InitWar\GameServer-master\GameServerApp\Program.cs:line 11

How can I fix that?

**Comment by iCraysen** [comment] 2016-11-28 15:03
Download this: https://github.com/LeagueSandbox/LeagueSandbox-Default
And put the files at GameServer-master\GameServerApp\Content\Data\LeagueSandbox-Default

**Comment by FurkanS1821** [comment] 2016-11-28 16:33
Closing this as is not a real issue and is resolved.
@mrcyclo do a rebuild after that too.

**Closed by FurkanS1821** 2016-11-28 16:33 UTC

**Comment by MythicManiac** [comment] 2016-11-28 17:46
This can be caused by two reasons:
* The most recent restructure change that moved the submodule to another location didn't update to you properly
* You've not initialized git submodules

You can fetch the latest version of the submodule always by running `git submodule update`. If you haven't initialized them yet, remember to run `git submodule init` first.
